version: 2.1

jobs:
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "Waiting until response from staging..."
  deploy_staging:
    machine: true
    steps:
      - run: echo "integration tests backend"
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy production build"
  acceptances_tests_1:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  checkout_And_unit_test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  acceptances_tests_2:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances_tests_3:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances_tests_4:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  deploy_backend:
    machine: true
    steps:
      - run: echo "deploy backend"
workflows:
  build:
    jobs:
      - checkout_And_unit_test
      - deploy_backend:
          requires:
            - checkout_And_unit_test
      - deploy_staging:
          requires:
            - integration_tests_backend
      - integration_tests_backend:
          requires:
            - deploy_backend
      - acceptances_tests_1:
          requires:
            - deploy_staging
      - acceptances_tests_2:
          requires:
            - deploy_staging
      - acceptances_tests_3:
          requires:
            - deploy_staging
      - acceptances_tests_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptances_tests_1
            - acceptances_tests_2
            - acceptances_tests_3
            - acceptances_tests_4
